from http.cookiejar import CookieJar
from typing import Optional
import browser_cookie3
import sys
import os

COOKIES_FILE = 'etc/cookies'

def clear_console() -> None:
    os.system('cls' if os.name == 'nt' else 'clear')

def get_browser_cookies() -> Optional[CookieJar]:
    browsers = {
        1: browser_cookie3.firefox,
        2: browser_cookie3.chrome,
        3: browser_cookie3.edge,
    }

    while True:
        try:
            browser_id = int(input(
                '[1] firefox\n'
                '[2] chrome\n'
                '[3] edge\n'
                '[0] exit\n'
                'Choose your main browser: '
            ))
            if browser_id < 0 or browser_id > 3:
                raise ValueError
            elif browser_id == 0:
                return None

            return browsers.get(browser_id)(domain_name='youtube.com')
        except ValueError:
            clear_console()
            print('\033[91mНекорректный ввод. Введите число от 0 до 3\033[0m')
        except browser_cookie3.BrowserCookieError:
            clear_console()
            print('\033[91mБраузер не найден\033[0m')
        except Exception as e:
            print(f'\033[91mОшибка: {e}\033[0m')

def save_cookies() -> None:
    cookies = get_browser_cookies()
    if cookies is None:
        print('Выход...')
        sys.exit(0)

    try:
        with open(COOKIES_FILE, 'w') as f:
            f.write('# Netscape HTTP Cookie File\n# This file is generated by yt-dlp. Do not edit.\n')
            for cookie in cookies:
                f.write(
                    f'{cookie.domain}\t'
                    f'TRUE\t'
                    f'{cookie.path}\t'
                    f'TRUE\t'
                    f'{cookie.expires if cookie.expires is not None else 0}\t'
                    f'{cookie.name}\t'
                    f'{cookie.value}\n'
                )
        print('\033[32mCookies сохранены.\033[0m')
    except Exception as e:
        print(f'\033[91mОшибка при сохранении cookies: {e}\033[0m')

def check_cookies() -> None:
    if not os.path.exists(COOKIES_FILE):
        print('\033[91mФайл cookies не найден\033[0m')
        save_cookies()

if __name__ == '__main__':
    save_cookies()
